# coding: utf-8

"""
    Tree of Life public name API

    API for ToL Public name registry  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kh14@sanger.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.curators_api import CuratorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCuratorsApi(unittest.TestCase):
    """CuratorsApi unit test stubs"""

    def setUp(self):
        self.api = CuratorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_public_name(self):
        """Test case for add_public_name

        adds a public name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
