# coding: utf-8

"""
    Tree of Life public name API

    API for ToL Public name registry  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kh14@sanger.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.consumers_api import ConsumersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConsumersApi(unittest.TestCase):
    """ConsumersApi unit test stubs"""

    def setUp(self):
        self.api = ConsumersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_public_name(self):
        """Test case for search_public_name

        searches DToL public names  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
