# coding: utf-8

"""
    Tree of Life public name API

    API for ToL Public name registry  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kh14@sanger.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.public_name import PublicName  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicName(unittest.TestCase):
    """PublicName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicName(self):
        """Test PublicName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.public_name.PublicName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
