# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: v1.3.17
    file: '/gitlab/app.yml'

variables:
  APP_NAME: "tolid"
  SERVICE_NAME: "id"

  DISABLE_UI_LINT: "true"

build-apiv3:
  extends: .build
  needs:
    - job: lint-license
      optional: true
    - job: lint-python
      optional: true
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolid-apiv3"
    DOCKERFILE: "tolid-apiv3/Dockerfile"
    NAME: "apiv3"
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: never
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always
