# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: v1.3.18
    file: '/gitlab/app.yml'

variables:
  APP_NAME: tolid
  DISABLE_UI_LINT: "true"
  APIV2_IMAGE: $CI_REGISTRY_IMAGE/tolid-apiv2:$CI_COMMIT_SHA

deploy-package:
  stage: deploy
  image: node:14-alpine
  script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - cd tolid-ui/app/src/tol-ui
    - yarn install
    - yarn build
    - yarn publish
  when: manual

build-apiv2:
  extends: .build
  needs:
    - job: lint-license
      optional: true
    - job: lint-python
      optional: true
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolid-apiv2"
    DOCKERFILE: "tolid-apiv2/Dockerfile"
    NAME: "tolid-apiv2"
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
      when: never
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always

build-apiv2-dev:
  extends: .build-dev
  needs:
    - job: lint-license
      optional: true
    - job: lint-python
      optional: true
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "tolid-apiv2"
    DOCKERFILE: "tolid-apiv2/Dockerfile"
    NAME: "tolid-apiv2"
  rules:
    - if: $CI_COMMIT_REF_NAME != "dev"
      when: never
    - when: always

unit-test-apiv2:
  extends: .unit-test-python
  image: $APIV2_IMAGE
  variables:
    TEST_BASE_DIR: tolid-apiv2/
  needs:
    - job: build-apiv2
      optional: true
    - job: build-apiv2-dev
      optional: true
