# coding: utf-8

"""
    Tree of Life public name API

    API for ToL Public name registry  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kh14@sanger.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Tree of Life public name API",
    author_email="kh14@sanger.ac.uk",
    url="",
    keywords=["Swagger", "Tree of Life public name API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    API for ToL Public name registry  # noqa: E501
    """
)
