# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

FROM python:3.10

WORKDIR /app

ENV FLASK_ENV=development
ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y python3-pip

COPY tolid/tolid-api/app/requirements.txt .
RUN pip3 --no-cache-dir install -r requirements.txt

# We install the tol-sdk here in editable mode
VOLUME ["/packages"]

# only copy tol-sdk into /packages if an exact match is found. Only upgrade to local if copied
COPY tol-sd[k]/ /packages/tol-sdk/
RUN if [ -d /packages/tol-sdk/src ] ; then pip3 install --editable /packages/tol-sdk[api_base2,postgresql]; fi;

COPY tolid/tolid-api/app /app
COPY tolid/tolid-api/migrations /migrations

CMD flask --app run run --debugger --port 80 --host 0.0.0.0
