# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

FROM python:3.10

WORKDIR /app

ENV FLASK_ENV=development
ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y python3-pip

COPY tolid/tolid-api/app/requirements.txt .
RUN pip3 --no-cache-dir install -r requirements.txt

COPY tolid/tolid-api/app /app
COPY tolid/tolid-api/migrations /migrations

CMD flask --app run run --debugger --port 80 --host 0.0.0.0
