# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

FROM python:3.12

WORKDIR /app

ENV FLASK_ENV = development
ENV PYTHONPATH = /app
ENV PYTHONDONTWRITEBYTECODE = 1

COPY ./app/requirements.txt .
RUN pip3 --no-cache-dir install -r requirements.txt

COPY ./requirements-test.txt .
RUN pip3 --no-cache-dir install -r requirements-test.txt

COPY ./app /app
COPY ./migrations /migrations

WORKDIR /app/test