# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.tax_spec import TaxSpec  # noqa: F401,E501
from swagger_server import util


class TaxonSpecimen(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_rows: List[TaxSpec]=None):  # noqa: E501
        """TaxonSpecimen - a model defined in Swagger

        :param data_rows: The data_rows of this TaxonSpecimen.  # noqa: E501
        :type data_rows: List[TaxSpec]
        """
        self.swagger_types = {
            'data_rows': List[TaxSpec]
        }

        self.attribute_map = {
            'data_rows': 'dataRows'
        }
        self._data_rows = data_rows

    @classmethod
    def from_dict(cls, dikt) -> 'TaxonSpecimen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaxonSpecimen of this TaxonSpecimen.  # noqa: E501
        :rtype: TaxonSpecimen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_rows(self) -> List[TaxSpec]:
        """Gets the data_rows of this TaxonSpecimen.


        :return: The data_rows of this TaxonSpecimen.
        :rtype: List[TaxSpec]
        """
        return self._data_rows

    @data_rows.setter
    def data_rows(self, data_rows: List[TaxSpec]):
        """Sets the data_rows of this TaxonSpecimen.


        :param data_rows: The data_rows of this TaxonSpecimen.
        :type data_rows: List[TaxSpec]
        """

        self._data_rows = data_rows
