# coding: utf-8

# flake8: noqa

"""
    Tree of Life public name API

    API for ToL Public name registry  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kh14@sanger.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.consumers_api import ConsumersApi
from swagger_client.api.curators_api import CuratorsApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.public_name import PublicName
