# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

FROM python:3.10

WORKDIR /app

ENV FLASK_ENV=development
ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y python3-pip

COPY ./app/requirements.txt .
RUN pip3 --no-cache-dir install -r requirements.txt

COPY ./requirements-test.txt .
RUN pip3 --no-cache-dir install -r requirements-test.txt

COPY ./app /app
