apiVersion: apps/v1
kind: Deployment
metadata:
  name: tolid-apiv2
  labels:
    {{- include "tolid-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: tolid-apiv2
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Subcharts.tolcore.Template.BasePath "/configmaps/api.yaml") .Subcharts.tolcore | sha256sum }}
        image: {{ .Values.tolcore.image.tag }}
      labels:
        app: tolid-apiv2
    spec:
      {{- with .Values.tolcore.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tolid-apiv2
          envFrom:
            - configMapRef:
                name: '{{ include "tol-core.api.fullname" .Subcharts.tolcore }}'
          env:
            - name: API_PATH
              value: {{ .Values.tolcore.apiv2.path | quote }}
            {{- if .Values.tolcore.db.enabled }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Subcharts.tolcore.Values.db.initdbSecretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Subcharts.tolcore.Values.db.initdbSecretName }}
                  key: password
            - name: DB_URI
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@{{ include `tol-core.db.host` .Subcharts.tolcore }}:{{ include `tol-core.db.port` .Subcharts.tolcore }}/{{ include `tol-core.db.name` .Subcharts.tolcore }}"
            {{- else }}
            - name: DB_URI
              value: {{ include "tol-core.db.uri" .Subcharts.tolcore }}
            {{- end }}
          image: "{{- .Values.tolcore.image.repository }}/tolid-apiv2:{{ .Values.tolcore.image.tag }}"
          imagePullPolicy: {{ .Values.tolcore.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: '{{ .Values.tolcore.apiv2.probe_url }}'
              port: http
          readinessProbe:
            httpGet:
              path: '{{ .Values.tolcore.apiv2.probe_url }}'
              port: http
            initialDelaySeconds: 10
