# coding: utf-8

"""
    Tree of Life public name API

    API for ToL Public name registry  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kh14@sanger.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ConsumersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def search_public_name(self, **kwargs):  # noqa: E501
        """searches DToL public names  # noqa: E501

        By passing in the appropriate options, you can search for available public names in the system   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_public_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str search_string: pass an optional search string for looking up a public name
        :param int skip: number of records to skip for pagination
        :param int limit: maximum number of records to return
        :return: list[PublicName]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_public_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.search_public_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def search_public_name_with_http_info(self, **kwargs):  # noqa: E501
        """searches DToL public names  # noqa: E501

        By passing in the appropriate options, you can search for available public names in the system   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_public_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str search_string: pass an optional search string for looking up a public name
        :param int skip: number of records to skip for pagination
        :param int limit: maximum number of records to return
        :return: list[PublicName]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['search_string', 'skip', 'limit']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_public_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'search_string' in params:
            query_params.append(('searchString', params['search_string']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('skip', params['skip']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/public-name', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[PublicName]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
